### ISSUE TITLE
suggestion: have the notebook that comes up in binder demo already working

### ISSUE THREAD

**Issue by fomightez** [xiaohk/stickyland#2]
Add  configuration files so that the demo notebook works when it opens a session served by MyBinder.   
Or add the `%pip install` commands necessary inside the demo notebook.

**Comment by xiaohk** [comment]
Nice suggestion! I have added a `requirements.txt` (fa334f5d126d049f943cee3b51ba1e33a75b031e) so that Binder would install all dependencies for the demo notebooks.

I also added a JupyterLite demo (hosted as a GitHub page): [![Lite](https://gist.githubusercontent.com/xiaohk/9b9f7c8fa162b2c3bc3251a5c9a799b2/raw/911a2ebee8d8044480f7bcaecac0a9483f735b74/lite-badge-small.svg)](https://xiaohk.github.io/stickyland/) JupyterLite is so cool!

**Comment by xiaohk** [comment]
The configuration file made binder load extremely slow 😄. I changed it to use `!pip install` instead.

**Comment by fomightez** [comment]
That's great it works with JupyterLite too!

Preferably use `%pip install` or no symbol and let automagics handle. The magics `%pip` and `%conda` were added a few years ago to overcome the shortcomings of `!pip install`.

**Comment by xiaohk** [comment]
> That's great it works with JupyterLite too!
> 
> Preferably use `%pip install` or no symbol and let automagics handle. The magics `%pip` and `%conda` were added a few years ago to overcome the shortcomings of `!pip install`.

Oh I didn't know that. Thanks! Just changed it to `%pip install`.
