### ISSUE TITLE
Floating cells not displayed in RetroLab (JupyterLite)

### ISSUE THREAD

**Issue by jtpio** [xiaohk/stickyland#3]
Hi,

Really slick extension!

It's really great that it also works with JupyterLite.

However in the RetroLab interface it looks like the floating cells are not displayed?

https://user-images.githubusercontent.com/591645/157658752-3564d670-519f-4225-bce4-787bb4299b95.mp4

The dev tools console seems to be showing some errors though:

![image](https://user-images.githubusercontent.com/591645/157659091-f85fd242-3615-4893-8a9a-9967b8c49036.png)

**Comment by xiaohk** [comment]
Hi @jtpio, thanks for raising the issue, and sorry for the late reply! It's been an insane week for me. I will take a look and try to fix it soon 🙏

**Comment by jtpio** [comment]
Hey @xiaohk no problem! Just wanted to bring that up because having it run in the retro / notebook UI would be really cool.

Really nice extension by the way!

**Comment by xiaohk** [comment]
Thanks again for raising this issue! This error is due to different HTML element names in JupyterLab and RetroLab. With the [new release v0.2.1](https://github.com/xiaohk/stickyland/releases/tag/v0.2.1), the floating window is now working in RetroLab / [Jupyter Notebook (v7.0.0a2 pre-release)](https://github.com/jupyter/notebook/tree/v7.0.0a2). The JupyterLite github page is also updated :P

I didn't know that Jupyter Notebook v7 will be based on RetroLab! This is a good news for all Lab extension developers!! Good to see Notebook users will also be able to use StickyLand soon.

https://user-images.githubusercontent.com/15007159/160261417-1f92521e-a353-4f72-b223-d2fa7c0b058b.mp4

**Comment by jtpio** [comment]
Really nice, thanks!
